services:
  db:
    image: postgres:16-alpine
    container_name: concurseiro_db
    environment:
      POSTGRES_USER: concurseiro
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurseiro_db
    ports:
      - "5432:5432"
    volumes:
      - concurseiro_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U concurseiro -d concurseiro_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: concurseiro_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  concurseiro_pgdata:
